# Generated by Django 5.0.6 on 2024-05-11 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='inventaris',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harga', models.CharField(max_length=25)),
                ('pembelian', models.TextField()),
                ('peringatan', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
